"""Quality gate helpers for API contract test results.

This module is intentionally tolerant of small report-shape changes because
API contract runs may be generated by live HTTP mode or in-process mode.
"""
from __future__ import annotations

from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional
import json

DEFAULT_RESULTS = Path("local_data/api/api_contract_results.json")
DEFAULT_OUTPUT = Path("local_data/api/api_contract_quality.json")


@dataclass
class QualityCheck:
    name: str
    status: str
    message: str

    @property
    def ok(self) -> bool:
        return self.status.lower() == "ok"


@dataclass
class ApiContractQuality:
    status: str
    summary: Dict[str, Any]
    checks: List[QualityCheck]

    def to_json_dict(self) -> Dict[str, Any]:
        return {
            "status": self.status,
            "summary": self.summary,
            "checks": [asdict(check) for check in self.checks],
        }


def _load_json(path: Path) -> Optional[Dict[str, Any]]:
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    return data if isinstance(data, dict) else None


def _norm(value: Any) -> str:
    return str(value or "").strip().lower().replace("-", "_").replace(" ", "_")


def _case_name(case: Mapping[str, Any]) -> str:
    for key in ("id", "case_id", "name", "case", "label"):
        value = case.get(key)
        if value:
            return str(value)
    return ""


def _case_status(case: Mapping[str, Any]) -> str:
    return _norm(case.get("status") or case.get("result") or case.get("outcome"))


def _case_passed(case: Mapping[str, Any]) -> bool:
    status = _case_status(case)
    return status in {"pass", "passed", "ok", "success"}


def _get_cases(data: Mapping[str, Any]) -> List[Mapping[str, Any]]:
    for key in ("cases", "case_results", "results", "checks"):
        value = data.get(key)
        if isinstance(value, list):
            return [item for item in value if isinstance(item, Mapping)]
    # Some older reports stored a dict keyed by case name.
    value = data.get("case_results") or data.get("results")
    if isinstance(value, Mapping):
        out: List[Mapping[str, Any]] = []
        for key, item in value.items():
            if isinstance(item, Mapping):
                merged = dict(item)
                merged.setdefault("id", key)
                out.append(merged)
        return out
    return []


def _status_counts(data: Mapping[str, Any], cases: List[Mapping[str, Any]]) -> Dict[str, int]:
    raw_counts = data.get("status_counts")
    if isinstance(raw_counts, Mapping):
        return {str(k).lower(): int(v) for k, v in raw_counts.items() if isinstance(v, (int, float))}
    passed = sum(1 for case in cases if _case_passed(case))
    failed = sum(1 for case in cases if not _case_passed(case))
    return {"pass": passed, "fail": failed}


def _case_by_keywords(cases: Iterable[Mapping[str, Any]], *keywords: str) -> Optional[Mapping[str, Any]]:
    wanted = [_norm(k) for k in keywords]
    for case in cases:
        name = _norm(_case_name(case))
        if all(keyword in name for keyword in wanted):
            return case
    return None


def _case_ok(cases: List[Mapping[str, Any]], *keywords: str) -> bool:
    case = _case_by_keywords(cases, *keywords)
    return bool(case and _case_passed(case))


def _add_check(checks: List[QualityCheck], name: str, ok: bool, message: str) -> None:
    checks.append(QualityCheck(name=name, status="OK" if ok else "FAIL", message=message))


def evaluate_api_contract_quality(
    results_path: Path | str = DEFAULT_RESULTS,
    *,
    min_total: int = 1,
    require_slow: bool = False,
) -> ApiContractQuality:
    path = Path(results_path)
    data = _load_json(path)
    checks: List[QualityCheck] = []

    if data is None:
        summary = {
            "api_contract_results_present": False,
            "api_contract_status": "missing",
            "api_contract_total": 0,
            "api_contract_pass": 0,
            "api_contract_fail": 0,
            "api_contract_mode": "unknown",
            "api_contract_base_url": None,
            "api_contract_status_endpoint_ok": False,
            "api_contract_part_lookup_ok": False,
            "api_contract_page_lookup_ok": False,
            "api_contract_trace_vector_ok": False,
            "api_contract_ask_ok": False,
            "api_contract_feedback_round_trip_ok": False,
            "api_contract_feedback_summary_ok": False,
            "api_contract_slow_cases": 0,
            "api_contract_slow_pass": 0,
        }
        _add_check(checks, "api_contract_results_present", False, f"API contract results are missing at {path}.")
        return ApiContractQuality(status="fail", summary=summary, checks=checks)

    cases = _get_cases(data)
    counts = _status_counts(data, cases)
    total = int(data.get("total") or data.get("total_cases") or len(cases) or sum(counts.values()))
    passed = int(counts.get("pass", counts.get("passed", counts.get("ok", 0))))
    failed = int(counts.get("fail", counts.get("failed", 0)))
    if total and not passed and not failed and cases:
        passed = sum(1 for case in cases if _case_passed(case))
        failed = len(cases) - passed

    report_status = _norm(data.get("status")) or ("ok" if failed == 0 and total >= min_total else "fail")
    status_ok = report_status in {"ok", "pass", "passed", "success"}

    status_endpoint_ok = _case_ok(cases, "status")
    part_lookup_ok = _case_ok(cases, "part", "lookup") or _case_ok(cases, "part_prompt")
    page_lookup_ok = _case_ok(cases, "page", "lookup") or _case_ok(cases, "page_prompt")
    trace_vector_ok = _case_ok(cases, "trace", "vector") or _case_ok(cases, "vector", "payload")
    ask_ok = _case_ok(cases, "ask") or _case_ok(cases, "rag_exact")
    feedback_round_trip_ok = _case_ok(cases, "feedback", "round")
    feedback_summary_ok = _case_ok(cases, "feedback", "summary")

    slow_cases = 0
    slow_pass = 0
    for case in cases:
        name = _norm(_case_name(case))
        is_slow = bool(case.get("slow") or case.get("is_slow") or "slow" in name or "broad_summary" in name)
        if is_slow:
            slow_cases += 1
            if _case_passed(case):
                slow_pass += 1

    summary = {
        "api_contract_results_present": True,
        "api_contract_status": "ok" if status_ok else report_status or "fail",
        "api_contract_mode": data.get("mode") or data.get("run_mode") or "unknown",
        "api_contract_base_url": data.get("base_url"),
        "api_contract_total": total,
        "api_contract_pass": passed,
        "api_contract_fail": failed,
        "api_contract_status_endpoint_ok": status_endpoint_ok,
        "api_contract_part_lookup_ok": part_lookup_ok,
        "api_contract_page_lookup_ok": page_lookup_ok,
        "api_contract_trace_vector_ok": trace_vector_ok,
        "api_contract_ask_ok": ask_ok,
        "api_contract_feedback_round_trip_ok": feedback_round_trip_ok,
        "api_contract_feedback_summary_ok": feedback_summary_ok,
        "api_contract_slow_cases": slow_cases,
        "api_contract_slow_pass": slow_pass,
    }

    _add_check(checks, "api_contract_results_present", True, f"API contract results are present at {path}.")
    _add_check(checks, "api_contract_results_status", status_ok, f"API contract report status is {report_status}.")
    _add_check(checks, "api_contract_cases", total >= min_total, f"API contract total cases={total}; minimum is {min_total}.")
    _add_check(checks, "api_contract_failures", failed == 0, f"API contract failed cases={failed}; expected 0.")
    _add_check(checks, "api_contract_status_endpoint", status_endpoint_ok, "Status endpoint contract passed.")
    _add_check(checks, "api_contract_part_lookup", part_lookup_ok, "Part lookup endpoint contract passed.")
    _add_check(checks, "api_contract_page_lookup", page_lookup_ok, "Page lookup endpoint contract passed.")
    _add_check(checks, "api_contract_trace_vector", trace_vector_ok, "Vector trace endpoint contract passed.")
    _add_check(checks, "api_contract_ask_endpoint", ask_ok, "Ask endpoint contract passed.")
    _add_check(checks, "api_contract_feedback_round_trip", feedback_round_trip_ok, "Feedback round-trip endpoint contract passed.")
    _add_check(checks, "api_contract_feedback_summary", feedback_summary_ok, "Feedback summary endpoint contract passed.")
    if require_slow:
        _add_check(checks, "api_contract_slow_case", slow_cases > 0 and slow_pass == slow_cases, f"Slow API contract cases passed: {slow_pass}/{slow_cases}.")

    overall_ok = all(check.ok for check in checks)
    return ApiContractQuality(status="ok" if overall_ok else "fail", summary=summary, checks=checks)


def write_api_contract_quality(quality: ApiContractQuality, output_path: Path | str = DEFAULT_OUTPUT) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(quality.to_json_dict(), indent=2, sort_keys=True), encoding="utf-8")
    return path


# Backward-compatible aliases used by older scripts/tests.
build_api_contract_quality = evaluate_api_contract_quality
write_quality_report = write_api_contract_quality
