#!/usr/bin/env python3
"""Streamlit web app for exploring word-context graphs with Gemma.

This app wraps the embed script functionality into an interactive UI where you can:
- Input a seed word
- Control the number of related words and context focus
- View the generated graph in real time
"""

import json
from collections import defaultdict

import streamlit as st

# Try importing the Ollama client. If it's not available, define a placeholder
# `chat` function that raises a clear error when called. This allows the Streamlit
# app to load and show a helpful message in the UI instead of crashing at import time.
try:
    from ollama import ResponseError, chat
except Exception as _import_err:
    ResponseError = Exception

    def chat(*args, **kwargs):
        raise RuntimeError(
            "The 'ollama' package is not installed in this environment. "
            "Install it into the project's venv with:\n"
            ".venv\\Scripts\\python.exe -m pip install ollama\n"
            "or run Streamlit using the venv python (python -m streamlit run ...)."
        )


MODEL = "gemma3:4b"
SYSTEM_PROMPT = (
    "You help build a small context graph. "
    "Return only concise JSON with related words and short edge reasons."
)

#!/usr/bin/env python3  # Shebang so script can be run directly on Unix systems
"""Streamlit web app for exploring word-context graphs with Gemma.

This app wraps the embed script functionality into an interactive UI where you can:
- Input a seed word
- Control the number of related words and context focus
- View the generated graph in real time
"""

import json  # Used to parse JSON model output
from collections import defaultdict  # Used to build adjacency lists for the graph

import streamlit as st  # Streamlit library for the web UI

# Attempt to import the Ollama client; if it's unavailable, provide a helpful
# placeholder so the app can load and display an error rather than crashing.
try:
    from ollama import ResponseError, chat
except Exception:
    ResponseError = Exception

    def chat(*args, **kwargs):
        # Raise a clear runtime error when the real client is absent
        raise RuntimeError(
            "The 'ollama' package is not installed in this environment. "
            "Install it into the project's venv with:\n"
            ".venv\\Scripts\\python.exe -m pip install ollama\n"
            "or run Streamlit using the venv python (python -m streamlit run ...)."
        )


MODEL = "gemma3:4b"  # Local Ollama model to query
SYSTEM_PROMPT = (
    "You help build a small context graph. "
    "Return only concise JSON with related words and short edge reasons."
)


def request_related_words(seed: str, focus: str, neighbors: int) -> dict[str, object]:
    """Send a prompt to the model asking for related words in compact JSON.

    Returns the parsed JSON on success or a fallback dict containing the raw
    output when parsing fails.
    """
    prompt = (
        "Create a compact JSON object for a word-context graph. "
        f"Seed word: {seed}. "
        f"Context focus: {focus}. "
        f"Return exactly {neighbors} related words. "
        "Use this schema: {\"seed\": string, \"focus\": string, \"related\": ["
        "{\"word\": string, \"reason\": string}]} . "
        "Keep reasons short and specific."
    )

    response = chat(
        MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        stream=False,
    )

    content = response["message"]["content"]  # Extract content text
    try:
        return json.loads(content)  # Parse content as JSON
    except json.JSONDecodeError:
        # On parse failure, return a fallback structure with the raw output
        return {"seed": seed, "focus": focus, "related": [], "raw_output": content}


def build_graph(seed: str, related: list[dict[str, str]]) -> dict[str, set[str]]:
    """Create a simple bidirectional adjacency list from related-word entries."""
    graph = defaultdict(set)
    for item in related:
        word = item.get("word", "").strip()
        if not word:
            continue
        graph[seed].add(word)
        graph[word].add(seed)
    return dict(graph)


def main():
    # Configure page layout and header
    st.set_page_config(page_title="Context Graph Explorer", layout="wide")
    st.title("🌐 Word Context Graph with Gemma")
    st.markdown("Enter a seed word and explore its context through a word graph generated by Gemma.")

    # Sidebar: inputs for seed, neighbor count, and context focus
    with st.sidebar:
        st.header("Graph Settings")
        seed = st.text_input("Seed word", value="embedding", help="The starting word for the context graph.")
        neighbors = st.slider("Number of neighbors", min_value=3, max_value=20, value=8, help="How many related words Gemma should generate.")
        focus = st.text_input("Context focus", value="word usage in technical text", help="What context to bias the related words toward.")
        generate = st.button("Generate Graph", type="primary")

    # Main area: trigger query and render results
    if generate or "payload" in st.session_state:
        if generate:
            with st.spinner("Querying Gemma..."):
                try:
                    payload = request_related_words(seed, focus, neighbors)
                    st.session_state.payload = payload
                except ResponseError as error:
                    st.error(f"Ollama error: {error}. Make sure '{MODEL}' is installed and running.")
                    return

        payload = st.session_state.get("payload", {})
        related = payload.get("related", [])
        graph = build_graph(seed, related if isinstance(related, list) else [])

        # Metrics: Seed, node count, and edge count
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Seed Word", seed)
        with col2:
            st.metric("Total Nodes", len(graph))
        with col3:
            total_edges = sum(len(neighbors) for neighbors in graph.values()) // 2
            st.metric("Edges", total_edges)

        st.divider()

        # Show nodes, edges and reasons side-by-side
        col_nodes, col_reasons = st.columns([1, 1])

        with col_nodes:
            st.subheader("Nodes & Edges")
            with st.expander("Node List", expanded=True):
                nodes_text = "\n".join(f"• {node}" for node in sorted(graph))
                st.text(nodes_text if nodes_text else "No nodes found.")

            with st.expander("Edge List"):
                edges = []
                for node in sorted(graph):
                    for neighbor in sorted(graph[node]):
                        if node < neighbor:
                            edges.append(f"{node} ↔ {neighbor}")
                edges_text = "\n".join(edges)
                st.text(edges_text if edges_text else "No edges found.")

        with col_reasons:
            st.subheader("Relationship Reasons")
            if isinstance(related, list) and related:
                for item in related:
                    word = item.get("word", "").strip()
                    reason = item.get("reason", "").strip()
                    if word:
                        st.markdown(f"**{word}:** {reason}")
            else:
                st.info("No relationship data available.")

        # If model parsing failed, show raw text for debugging
        raw_output = payload.get("raw_output")
        if raw_output:
            with st.expander("Raw Model Output"):
                st.code(raw_output, language="json")


if __name__ == "__main__":
    main()
