#!/usr/bin/env python3
"""Streamlit web app for exploring word-context graphs with Gemma.

The app asks Ollama for JSON describing related words, turns that into a small
graph, and falls back to showing the raw model output when parsing fails.
"""

from __future__ import annotations

import json
import re
from collections import defaultdict

import streamlit as st

try:
    from ollama import ResponseError, chat
except Exception:
    ResponseError = Exception

    def chat(*args, **kwargs):
        raise RuntimeError(
            "The 'ollama' package is not installed in this environment. "
            "Install it into the project's venv with:\n"
            ".venv\\Scripts\\python.exe -m pip install ollama\n"
            "or run Streamlit using the venv python (python -m streamlit run ...)."
        )


MODEL = "gemma3:4b"
SYSTEM_PROMPT = (
    "You help build a small context graph. "
    "Return only valid JSON with related words and short edge reasons."
)


def extract_json_text(content: str) -> str:
    """Strip markdown fences or surrounding text and return a JSON object string."""
    text = content.strip()

    fenced = re.search(r"```(?:json)?\s*(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
    if fenced:
        text = fenced.group(1).strip()

    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        text = text[start : end + 1].strip()

    return text


def request_related_words(seed: str, focus: str, neighbors: int) -> dict[str, object]:
    prompt = (
        "Create a compact JSON object for a word-context graph. "
        f"Seed word: {seed}. "
        f"Context focus: {focus}. "
        f"Return exactly {neighbors} related words. "
        'Use this schema: {"seed": string, "focus": string, "related": ['
        '{"word": string, "reason": string}]}. '
        "Keep reasons short and specific. Return JSON only. No markdown. No commentary."
    )

    response = chat(
        MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        stream=False,
    )

    content = response["message"]["content"]
    json_text = extract_json_text(content)

    try:
        payload = json.loads(json_text)
    except json.JSONDecodeError:
        return {"seed": seed, "focus": focus, "related": [], "raw_output": content}

    if not isinstance(payload, dict):
        return {"seed": seed, "focus": focus, "related": [], "raw_output": content}

    payload.setdefault("seed", seed)
    payload.setdefault("focus", focus)
    payload.setdefault("related", [])
    return payload


def build_graph(seed: str, related: list[dict[str, str]]) -> dict[str, set[str]]:
    graph = defaultdict(set)
    for item in related:
        if not isinstance(item, dict):
            continue
        word = item.get("word", "").strip()
        if not word:
            continue
        graph[seed].add(word)
        graph[word].add(seed)
    return dict(graph)


def build_graph_dot(seed: str, related: list[dict[str, str]]) -> str:
    """Build a Graphviz DOT string for the current seed and related words."""
    lines = [
        'graph G {',
        '  rankdir="LR";',
        '  splines=true;',
        '  overlap=false;',
        '  node [shape=circle, style=filled, fillcolor="#E8F1FF", color="#2F6FED", fontname="Arial"];',
        '  edge [color="#6B7280", penwidth=1.5];',
        f'  "{seed}" [fillcolor="#1D4ED8", fontcolor="white", penwidth=2.0];',
    ]

    seen_edges = set()
    for item in related:
        if not isinstance(item, dict):
            continue
        word = item.get("word", "").strip()
        if not word:
            continue
        edge = tuple(sorted((seed, word)))
        if edge in seen_edges:
            continue
        seen_edges.add(edge)
        reason = item.get("reason", "").strip().replace('"', '\\"')
        lines.append(f'  "{seed}" -- "{word}" [label="{reason}"];')

    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    st.set_page_config(page_title="Context Graph Explorer", layout="wide")
    st.title("🌐 Word Context Graph with Gemma")
    st.markdown("Enter a seed word and explore its context through a word graph generated by Gemma.")

    with st.sidebar:
        st.header("Graph Settings")
        seed = st.text_input("Seed word", value="embedding", help="The starting word for the context graph.")
        neighbors = st.slider(
            "Number of neighbors",
            min_value=3,
            max_value=20,
            value=8,
            help="How many related words Gemma should generate.",
        )
        focus = st.text_input(
            "Context focus",
            value="word usage in technical text",
            help="What context to bias the related words toward.",
        )
        generate = st.button("Generate Graph", type="primary")

    if generate or "payload" in st.session_state:
        if generate:
            with st.spinner("Querying Gemma..."):
                try:
                    st.session_state.payload = request_related_words(seed, focus, neighbors)
                except ResponseError as error:
                    st.error(f"Ollama error: {error}. Make sure '{MODEL}' is installed and running.")
                    return

        payload = st.session_state.get("payload", {})
        related = payload.get("related", [])
        graph = build_graph(seed, related if isinstance(related, list) else [])

        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Seed Word", seed)
        with col2:
            st.metric("Total Nodes", len(graph))
        with col3:
            total_edges = sum(len(neighbors) for neighbors in graph.values()) // 2
            st.metric("Edges", total_edges)

        st.divider()

        col_nodes, col_reasons = st.columns([1, 1])

        with col_nodes:
            st.subheader("Nodes & Edges")
            with st.expander("Node List", expanded=True):
                nodes_text = "\n".join(f"• {node}" for node in sorted(graph))
                st.text(nodes_text if nodes_text else "No nodes found.")

            with st.expander("Edge List"):
                edges = []
                for node in sorted(graph):
                    for neighbor in sorted(graph[node]):
                        if node < neighbor:
                            edges.append(f"{node} ↔ {neighbor}")
                edges_text = "\n".join(edges)
                st.text(edges_text if edges_text else "No edges found.")

        with col_reasons:
            st.subheader("Relationship Reasons")
            if isinstance(related, list) and related:
                for item in related:
                    if not isinstance(item, dict):
                        continue
                    word = item.get("word", "").strip()
                    reason = item.get("reason", "").strip()
                    if word:
                        st.markdown(f"**{word}:** {reason}")
            else:
                st.info("No relationship data available.")

        st.divider()
        st.subheader("Graph Diagram")
        if isinstance(related, list) and related:
            st.graphviz_chart(build_graph_dot(seed, related), use_container_width=True)
        else:
            st.info("No diagram to show yet because there are no related words.")

        raw_output = payload.get("raw_output")
        if raw_output:
            with st.expander("Raw Model Output"):
                st.code(raw_output, language="json")


if __name__ == "__main__":
    main()
