import json
import zipfile
from pathlib import Path

from scripts.run_trace_net_sample_zip_fixed50_qa_v1 import (
    build_fixed50_questions_and_answers,
    inspect_sample_zip,
    render_question_answer_text,
    run,
)


def make_sample_zip(path: Path) -> None:
    metadata = '''<?xml version="1.0" encoding="UTF-8"?>
<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:mix="http://www.loc.gov/mix/" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink" LABEL="TEST MANUAL" OBJID="obj-123" TYPE="ResCarta Monograph Metadata v3.1">
 <mets:metsHdr CREATEDATE="2024-01-02T03:04:05" RECORDSTATUS="COMPLETE">
  <mets:agent ROLE="CREATOR" TYPE="ORGANIZATION"><mets:name>Unit Tool</mets:name><mets:note>Generated by unit test</mets:note></mets:agent>
 </mets:metsHdr>
 <mets:dmdSec ID="DMD0001"><mets:mdWrap MDTYPE="MODS" MIMETYPE="text/xml"><mets:xmlData><mods:mods>
  <mods:titleInfo><mods:title>TEST MANUAL</mods:title></mods:titleInfo>
  <mods:name><mods:namePart>HDL</mods:namePart></mods:name>
  <mods:typeOfResource>text</mods:typeOfResource>
  <mods:genre>book</mods:genre>
  <mods:originInfo><mods:dateCaptured>2024-01-02</mods:dateCaptured><mods:issuance>monographic</mods:issuance></mods:originInfo>
  <mods:language><mods:languageTerm>eng</mods:languageTerm></mods:language>
  <mods:abstract>Sample abstract</mods:abstract>
  <mods:identifier type="local">local-123</mods:identifier>
  <mods:location><mods:url>local-123</mods:url></mods:location>
  <mods:part order="1"><mods:extent unit="pages"><mods:start>1</mods:start><mods:end>3</mods:end></mods:extent></mods:part>
 </mods:mods></mets:xmlData></mets:mdWrap></mets:dmdSec>
 <mets:amdSec ID="AMD0001"><mets:techMD ID="TMD0001"><mets:mdWrap MDTYPE="NISOIMG" MIMETYPE="text/xml"><mets:xmlData><mix:mix><mix:BasicImageParameters><mix:Format>
  <mix:MIMEType>image/tiff</mix:MIMEType><mix:ByteOrder>little-endian</mix:ByteOrder><mix:Compression><mix:CompressionScheme>4</mix:CompressionScheme></mix:Compression><mix:PhotometricInterpretation><mix:ColorSpace>1</mix:ColorSpace></mix:PhotometricInterpretation>
 </mix:Format></mix:BasicImageParameters></mix:mix></mets:xmlData></mets:mdWrap></mets:techMD></mets:amdSec>
 <mets:fileSec><mets:fileGrp ID="FG0001">
  <mets:file CHECKSUM="aaa" CHECKSUMTYPE="SHA-1" ID="FID0001" MIMETYPE="image/tiff" SIZE="10"><mets:FLocat LOCTYPE="URL" xlink:href="file://./00000001.tif"/></mets:file>
  <mets:file CHECKSUM="bbb" CHECKSUMTYPE="SHA-1" ID="FID0002" MIMETYPE="image/tiff" SIZE="20"><mets:FLocat LOCTYPE="URL" xlink:href="file://./00000002.tif"/></mets:file>
  <mets:file CHECKSUM="ccc" CHECKSUMTYPE="SHA-1" ID="FID0003" MIMETYPE="image/tiff" SIZE="30"><mets:FLocat LOCTYPE="URL" xlink:href="file://./00000003.tif"/></mets:file>
 </mets:fileGrp></mets:fileSec>
</mets:mets>'''
    with zipfile.ZipFile(path, "w") as z:
        z.writestr("metadata.xml", metadata)
        z.writestr("00000001.tif", b"1" * 10)
        z.writestr("00000002.tif", b"2" * 20)
        z.writestr("00000003.tif", b"3" * 30)


def test_inspect_sample_zip_reads_metadata_and_inventory(tmp_path):
    sample = tmp_path / "sample.zip"
    make_sample_zip(sample)
    facts = inspect_sample_zip(sample)
    assert facts["mets_root_label"] == "TEST MANUAL"
    assert facts["mets_reported_page_count"] == 3
    assert facts["zip_tiff_count"] == 3
    assert facts["mets_tiff_count"] == 3
    assert facts["zip_and_mets_tiff_counts_match"] is True
    assert facts["first_mets_file"]["file_id"] == "FID0001"
    assert facts["last_mets_file"]["href"] == "file://./00000003.tif"


def test_builds_exactly_50_questions(tmp_path):
    sample = tmp_path / "sample.zip"
    make_sample_zip(sample)
    facts = inspect_sample_zip(sample)
    records = build_fixed50_questions_and_answers(facts)
    assert len(records) == 50
    assert records[0]["question_id"] == "q01"
    assert records[-1]["question_id"] == "q50"
    assert any("TEST MANUAL" in r["answer"] for r in records)


def test_question_answer_text_shape(tmp_path):
    sample = tmp_path / "sample.zip"
    make_sample_zip(sample)
    records = build_fixed50_questions_and_answers(inspect_sample_zip(sample))
    text = render_question_answer_text(records)
    assert "Question 01:" in text
    assert "Answer 01:" in text
    assert "Question 50:" in text
    assert "Answer 50:" in text


def test_run_writes_outputs(tmp_path):
    sample = tmp_path / "sample.zip"
    out = tmp_path / "out"
    make_sample_zip(sample)
    summary = run(sample, out, print_answers=False)
    assert summary["quality_status"] == "PASS"
    assert summary["answered_count"] == 50
    assert (out / "answers.jsonl").exists()
    assert (out / "answers_question_answer.txt").exists()
    assert (out / "sample_zip_facts.json").exists()
    rows = [(json.loads(line)) for line in (out / "answers.jsonl").read_text().splitlines()]
    assert len(rows) == 50
    assert rows[0]["question"].startswith("What ZIP file")
