import json
import zipfile
from pathlib import Path

from scripts.run_trace_net_sample_zip_content_fixed50_qa_v1 import build_answers, parse_sample_zip, run


def make_sample_zip(path: Path, page_count: int = 3):
    file_records = []
    div_records = []
    for i in range(1, page_count + 1):
        fid = f"FID{i:04d}"
        fname = f"{i:08d}.tif"
        file_records.append(
            f'<mets:file CHECKSUM="{i:040x}" CHECKSUMTYPE="SHA-1" GROUPID="FG0001" ID="{fid}" MIMETYPE="image/tiff" SIZE="{1000+i}">'
            f'<mets:FLocat LOCTYPE="URL" xlink:href="file://./{fname}" xlink:type="simple"/>'
            f'</mets:file>'
        )
        div_records.append(
            f'<mets:div ADMID="AMD0001" LABEL="{i}" ORDER="{i}" TYPE="page" xlink:label="PPG{i:04d}"><mets:fptr FILEID="{fid}"/></mets:div>'
        )
    xml = f'''<?xml version="1.0" encoding="UTF-8"?>
<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:mix="http://www.loc.gov/mix/" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" LABEL="TEST TITLE" OBJID="obj/1" TYPE="ResCarta Monograph Metadata v3.1">
<mets:metsHdr CREATEDATE="2026-01-01T00:00:00" RECORDSTATUS="COMPLETE"><mets:agent ROLE="CREATOR" TYPE="ORGANIZATION"><mets:name>ResCarta Tools</mets:name><mets:note>Generated by test</mets:note></mets:agent></mets:metsHdr>
<mets:dmdSec ID="DMD0001"><mets:mdWrap MDTYPE="MODS" MIMETYPE="text/xml"><mets:xmlData><mods:mods>
<mods:titleInfo><mods:title>TEST TITLE</mods:title></mods:titleInfo>
<mods:name><mods:namePart>HDL</mods:namePart><mods:role><mods:roleTerm authority="marcrelator" type="code">own</mods:roleTerm><mods:roleTerm authority="marcrelator" type="text">Owner</mods:roleTerm></mods:role></mods:name>
<mods:typeOfResource>text</mods:typeOfResource><mods:genre authority="marcgt">book</mods:genre><mods:originInfo><mods:dateCaptured encoding="iso8601">2026-01-01</mods:dateCaptured><mods:issuance>monographic</mods:issuance></mods:originInfo>
<mods:language><mods:languageTerm authority="iso639-2b" type="code">eng</mods:languageTerm></mods:language><mods:abstract>Sample abstract</mods:abstract><mods:identifier type="local">obj/1</mods:identifier><mods:location><mods:url>obj/1</mods:url></mods:location><mods:part order="1"><mods:extent unit="pages"><mods:start>1</mods:start><mods:end>{page_count}</mods:end></mods:extent></mods:part>
</mods:mods></mets:xmlData></mets:mdWrap></mets:dmdSec>
<mets:amdSec ID="AMD0001"><mets:techMD ID="TMD0001"><mets:mdWrap MDTYPE="NISOIMG" MIMETYPE="text/xml"><mets:xmlData><mix:mix><mix:BasicImageParameters><mix:Format><mix:MIMEType>image/tiff</mix:MIMEType><mix:ByteOrder>little-endian</mix:ByteOrder><mix:Compression><mix:CompressionScheme>4</mix:CompressionScheme></mix:Compression><mix:PhotometricInterpretation><mix:ColorSpace>1</mix:ColorSpace></mix:PhotometricInterpretation></mix:Format></mix:BasicImageParameters></mix:mix></mets:xmlData></mets:mdWrap></mets:techMD></mets:amdSec>
<mets:fileSec><mets:fileGrp ID="FG0001">{''.join(file_records)}</mets:fileGrp></mets:fileSec>
<mets:structMap><mets:div TYPE="book">{''.join(div_records)}</mets:div></mets:structMap>
</mets:mets>'''
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("metadata.xml", xml)
        for i in range(1, page_count + 1):
            zf.writestr(f"{i:08d}.tif", b"x" * (1000 + i))


def test_parse_metadata_content(tmp_path):
    z = tmp_path / "metadata.zip"
    make_sample_zip(z, page_count=3)
    parsed = parse_sample_zip(z)
    assert parsed.mods["title"] == "TEST TITLE"
    assert parsed.mods["language_code"] == "eng"
    assert len(parsed.mets_files) == 3
    assert len(parsed.page_maps) == 3
    assert parsed.page_maps[0].basename == "00000001.tif"


def test_builds_exactly_50_question_answers(tmp_path):
    z = tmp_path / "metadata.zip"
    make_sample_zip(z, page_count=3)
    rows = build_answers(parse_sample_zip(z))
    assert len(rows) == 50
    assert rows[0]["question"].startswith("What ZIP file")
    assert all(r["answer"] for r in rows)


def test_run_writes_question_answer_output(tmp_path):
    z = tmp_path / "metadata.zip"
    out = tmp_path / "out"
    make_sample_zip(z, page_count=3)
    summary = run(z, out, show_progress=False, print_answers=False)
    assert summary["quality_status"] == "PASS"
    txt = (out / "answers_question_answer.txt").read_text(encoding="utf-8")
    assert "Question 01:" in txt
    assert "Answer 01:" in txt
    assert "Question 50:" in txt


def test_summary_is_json_and_safety_read_only(tmp_path):
    z = tmp_path / "metadata.zip"
    out = tmp_path / "out"
    make_sample_zip(z, page_count=3)
    run(z, out, show_progress=False, print_answers=False)
    data = json.loads((out / "summary.json").read_text(encoding="utf-8"))
    assert data["answer_permission_count"] == 0
    assert data["source_truth_mutation_allowed_count"] == 0
    assert data["write_attempt_count"] == 0
